services:
  book:
    build: .
    container_name: book
    ports:
      - 8080:8080
    depends_on:
      - postgres
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=cookbook'
      - 'POSTGRES_PASSWORD=geronimo'
      - 'POSTGRES_USER=user'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'PGDATA=/var/lib/postgresql/data/pgdata'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    ports:
      - '5432'
volumes:
  pgdata: