spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.rest.RepositoryRestMvcAutoConfiguration
  main:
    allow-bean-definition-overriding: true
  data:
    web:
      pageable:
        page-parameter: page
        size-parameter: page-size
        one-indexed-parameters: true
        default-page-size: 10
        max-page-size: 50
  application:
    name: book
  profiles:
    active: local
  flyway:
    enabled: false

server:
  port: 8080

springdoc:
  packagesToScan: "com.cook.book"
  pathsToMatch: "/**"