spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:cookbook;DB_CLOSE_DELAY=-1;
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    console:
      enabled: true
  flyway:
    enabled: false