spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/cookbook?currentSchema=cookbook
    username: user
    password: geronimo
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: cookbook
        show_sql: true
        use_sql_comments: true
        format_sql: true
        generate_statistics: false
        jdbc:
          fetch_size: 2000
          lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    schemas: cookbook
    locations: classpath:db